server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: Changsha #配置集群
        namespace: 432f5be3-ff68-473f-86ef-e7d43c8e990f #命名空间
    #        ephemeral: false #设置为永久实例
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/task/**

        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/course/**

        - id: relationship-service
          uri: lb://relationship-service
          predicates:
            - Path=/relationship/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            maxAge: 360000
            allow-credentials: true
            allowed-origins:
              - "http://localhost:80"
              - "http://localhost:8088"
              - "http://codebridge.cn"
              - "http://www.codebridge.cn"
              - "https://codebridge.cn"
              - "https://www.codebridge.cn"
            allowed-methods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowed-headers: "*"





