server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: Changsha #配置集群
#        namespace: 432f5be3-ff68-473f-86ef-e7d43c8e990f #命名空间
    #        ephemeral: false #设置为永久实例
    gateway:
      routes:
        - id: user-service-files
          uri: lb://user-service
          predicates:
              - Path=/files/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
#            - Path=/files/**




        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/tasks/**

        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/courses/**

        - id: relationship-service
          uri: lb://relationship-service
          predicates:
            - Path=/relationships/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            maxAge: 360000
            allow-credentials: true
            allowed-origins:
              - "http://127.0.0.1:80"
              - "http://128.0.0.1:8088"
              - "http://127.0.0.1:63343"
              - "http://127.0.0.1:63342"
              - "http://codebridge.cn"
              - "http://www.codebridge.cn"
              - "https://codebridge.cn"
              - "https://www.codebridge.cn"
              - "http://localhost:63343"
              - "http://localhost:63342"
            allowed-methods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowed-headers: "*"





