
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  application:
    name: user-service
  #          namespace: 432f5be3-ff68-473f-86ef-e7d43c8e990f #命名空间
  #        ephemeral: false #设置为永久实例
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: Changsha
      config:
        cluster-name: Changsha
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://home.codebridge.cn:3306/cb_user
    username: root
    password: Yy336699
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      pool-prepared-statements: true
  servlet:
    # 上传限定参数
    multipart:
      # 是否启用分段上传支持
      enabled: true
      # 最大请求大小
      max-request-size: 60MB
      # 最大文件的大小
      max-file-size: 50MB
      #上传文件的中间位置
  #      location: /User/webbershaw/temp

  mail:
    host: smtp.exmail.qq.com
    username: wenboxiao@stu.hunau.edu.cn
    password: Xiaoge0225
    default-encoding: utf-8
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm
mybatis:
  type-aliases-package: edu.codebridge.user.mapper
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
server:
  port: 8084
  servlet:
    session:
      cookie:

       # 设置 SameSite 属性为 None
        secure: true
        # 启用 Secure 属性
        comment:
        same-site: none
        name: SESSION








  # yml 配置如下
#  ssl:
#    key-store: classpath:www.webbershaw.fun.jks
#    key-store-password: f6wg4y97b27
#    key-store-type: JKS


azureblob:
  defaultEndpointsProtocol: https
  blobEndpoint: https://emue7eheidyf4vpnsa.blob.core.windows.net
  queueEndpoint: https://emue7eheidyf4vpnsa.square.core.windows.net
  tableEndpoint: https://emue7eheidyf4vpnsa.table.core.windows.net
  accountName: emue7eheidyf4vpnsa
  accountKey: ei06tW+9/NrXjGa38hXbIj7LbwnlfArksMfwtejW/MYtSqAWXyh0garzwtzMKAoYvoqIBV4K4TXk+AStYCGl1Q==
#










